### ISSUE TITLE
Usage with Typescript

### ISSUE THREAD

**Issue by SanderKnape** [bboure/serverless-appsync-simulator#137]
Hello. When using this plugin together with the `serverless-plugin-typescript` plugin, the simulator automatically looks in our `.build` directory to find the compiled Lambda functions.

However, it also attempts to find the `schema.graphql` in this same directory which fails as this file only exists in the root. I don't see an option to tell it to find the schema in a different location from the Lambda functions.

Running `cp schema.graphql .build/` before starting this plugin works, but that breaks hot reloading.

What's the proper way to use this plugin together with the Typescript plugin?

**Comment by bboure** [comment]
Hi,

By default, this plugin looks into the [servicePath](https://github.com/bboure/serverless-appsync-simulator/blob/master/src/getAppSyncConfig.js#L225), which is the root of your `serverless.yml` file.

It looks like `serverless-plugin-typescript` [overrides that path](https://github.com/serverless/serverless-plugin-typescript/blob/master/src/index.ts#L146).

[This is an issue I also encountered with [serverless-esbuild](https://github.com/floydspace/serverless-esbuild/issues/90) that has since been fixed.

IMO, I believe this is a bad practice, but I guess that there is not much we can do about it.

What I suggest is to create an option in this plugin to allow a custom basePath for these files (schema and mapping templates).

**Comment by SanderKnape** [comment]
Hi bboure, thanks for taking a look at this!

We're not using mapping templates, but I just added one as a test and I see it has the same issue as `.build` is added to the path:

`Error: ENOENT: no such file or directory, open '/Users/[...]/.build/mapping-templates/request.vtl`

I guess having two `location` options to 1) override the servicePath and 2) set the Lambda path to `.build` would fix this, but I agree the real issue is with the `serverless-plugin-typescript`.

**Comment by shawnmclean** [comment]
> Running cp schema.graphql .build/ before starting this plugin works, but that breaks hot reloading.

Can anyone explain how to implement this change?

**Comment by bboure** [comment]
> Can anyone explain how to implement this change?

We could add an option `basePath` that users could set in the serverless.yml in order to specify the path of the mapping templates and schemas. 
If present, use it everywhere we use the `servicePath`.

I'll try to find some time and implement this
