### ISSUE TITLE
Unknown operation name: TransactWriteItems

### ISSUE THREAD

**Issue by douglasgsouza** [bboure/serverless-appsync-simulator#37]
I'm trying to make a TransactWriteItems request to DynamoDB Local and I'm getting the following error message:

"message": "Unknown operation name: TransactWriteItems",
            "errorType": null,
            "data": null,
            "errorInfo": null,
            "path": [
                "createProduct"
            ],
            "locations": [
                {
                    "line": 2,
                    "column": 5,
                    "sourceName": "GraphQL request"
                }
            ]

My package.json dependencies:

"serverless-appsync-plugin": "^1.3.1",
"serverless-appsync-simulator": "^0.6.0",
"serverless-dynamodb-local": "^0.2.39",
"serverless-offline": "^6.4.0",
"serverless-stack-output": "^0.2.3"

**Comment by bboure** [comment]
@douglasgsouza Indeed. This plugin relies on amplify-cli under the hood. From what I can see, the `TransactWriteItems` operation [is not yet supported](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/data-loader/dynamo-db/index.ts#L29).

They don't support batch operations either. 
It might be worth it trying to open an issue or a PR in order to implement them.

**Comment by douglasgsouza** [comment]
> @douglasgsouza Indeed. This plugin relies on amplify-cli under the hood. From what I can see, the `TransactWriteItems` operation [is not yet supported](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-appsync-simulator/src/data-loader/dynamo-db/index.ts#L29).
> 
> They don't support batch operations either.
> It might be worth it trying to open an issue or a PR in order to implement them.

Thanks for the reply and sorry for that issue.
