### ISSUE TITLE
AppSync Simulator just hangs

### ISSUE THREAD

**Issue by adriantodt** [bboure/serverless-appsync-simulator#73]
**Describe the bug**
I tried to execute a lambda but it just hangs. Calling the lambda directly using the AWS CLI works, though. No logs are shown, even with `export SLS_DEBUG true` and `--verbose`

**To Reproduce**
The following plugins are used:
```yaml
plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-plugin-warmup
  - serverless-appsync-simulator
  - serverless-offline
  ```

Our AppSync uses Cognito User Pools + API Key as authentication methods, but I configured both the simulator as well as serverless-offline to use the same API key.

**Expected behavior**
I expected it to show a log or something, instead of just hanging.

**Screenshots**
![image](https://user-images.githubusercontent.com/6955035/105532895-3b1f7a80-5cca-11eb-89d3-3b0e66d21766.png)
Here's the screenshot of it hanging on GraphiQL.

**Additional context**
N/A

**Comment by cameroncf** [comment]
See #72 in which I am also seeing a problem with the plugin hanging. I also have multiple Auth methods.

Curious if you have AWS_IAM as the default authenticationType or if it's in additionalAuthenticationProviders? I've found that when using these two in combination (on live AppSync, not the simulator) that AppSync really wants IAM to be the primary with Cognito as secondary.

**Comment by adriantodt** [comment]
Almost... the default authenticationType is AMAZON_COGNITO_USER_POOLS and I have API_KEY in the additionalAuthenticationProviders.

**Comment by cameroncf** [comment]
Oh right - I misread your post. Not sure if flipping the order will help you or not.

**Comment by bboure** [comment]
@adriantodt I have seen this issue before too. This is not related to multi-auth though (at least in my case). Usually, it happens when there is a wrong config in the YML file or a bad VTL template.

Improving the logs is definitely something I'd like to see. For example, see the compiled request/response VTL. However, this is something that would need to be implemented in Amplify-cli.

I'll try to take some time to open a PR, or feel free to.

I will leave this issue open meanwhile. If yo find the root cause of your particular issue, please let us know.
