### ISSUE TITLE
Error AppSync Simulator: TypeError: Cannot read property 'findWrappedResource' of undefined

### ISSUE THREAD

**Issue by robboerman2** [bboure/serverless-appsync-simulator#9]
**Describe the bug**
on serverless start i get a error
AppSync Simulator: TypeError: Cannot read property 'findWrappedResource' of undefined

**To Reproduce**
Got the current serverless.yml setup custom like this:
`custom:
  name: ${self:service}-${self:provider.stage}
  dynamodb:
    start:
      port: 8039
  appsync-simulator:
    port: 6239
    dynamoDb:
      endpoint: "http://localhost:8039"
  serverless-offline:
    port: 4039
  appSync:
    authenticationType: API_KEY
    name: ${self:custom.name}
......
`
resulting in this:
<img width="1032" alt="Schermafbeelding 2019-12-23 om 13 14 13" src="https://user-images.githubusercontent.com/28255308/71357469-313abd80-2586-11ea-9b9c-b219a88d29a2.png">

any advise on how to solve this error?

**Comment by bboure** [comment]
Thanks for raising this issue.

Issue seems to come from the [cfn-resolver-lib](https://github.com/robessog/cfn-resolver-lib) dependency. [here](https://github.com/robessog/cfn-resolver-lib/blob/68a990808c027a84757a19792e8c7d9b309de992/src/nodeTypes/FnGetAttNode.js#L17)

[`Resources` is undefined here](https://github.com/robessog/cfn-resolver-lib/blob/68a990808c027a84757a19792e8c7d9b309de992/src/nodeTypes/FnGetAttNode.js#L9)

While this definitely looks like a bug in `cfn-resolver-lib`, It might also be that we are causing the issue because of how we use it.

I'll try to reproduce this

Could you please share your `serverless.yml` file? (or the relevant parts).

thanks

**Comment by robboerman2** [comment]
Great :) waiting on your fix then. this plugin looks amazing btw 👍 really something that the community was waiting on, to make debugging offline better

**Comment by bboure** [comment]
Should be fixed in v0.3.2

**Comment by robboerman2** [comment]
You are amazing! 🥇
